### ISSUE TITLE
Getting error in windows on start

### ISSUE THREAD

**Issue by RohithChittibommala** [jherr/create-mf-app#23]
when I run the app using the npm run start command I am getting this error

![image](https://user-images.githubusercontent.com/62145732/147630108-3b3912b9-5ae6-482f-aa44-52396d2171bd.png)

```text  Error: listen EACCES: permission denied 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1302:21)
    at listenInCluster (node:net:1367:12)
    at Server.listen (node:net:1454:7)
    at READ_WRITE (C:\Users\rohit\Desktop\open-board\node_modules\webpack-dev-server\lib\Server.js:3221:23) 
   at new Promise (<anonymous>)
    at Server.start (C:\Users\rohit\Desktop\open-board\node_modules\webpack-dev-server\lib\Server.js:3219:7)
    at async Command.<anonymous> (C:\Users\rohit\Desktop\open-board\node_modules\@webpack-cli\serve\lib\index.js:242:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\Users\rohit\Desktop\open-board\node_modules\webpack-cli\lib\webpack-cli.js:1672:7) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}```

**Comment by jherr** [comment]
This means that you already have something running on port 3000.

**Comment by RohithChittibommala** [comment]
@jherr  any guide to use .env variables, btw appreciate your efforts in making dev life easy

**Comment by jherr** [comment]
> @jherr any guide to use .env variables, btw appreciate your efforts in making dev life easy

Guidance on using .env variables in general? Or in regards to this application in particular? If you have general questions please visit my Discord server and ask your questions there. https://discord.gg/eUBvqyzJ
