### ISSUE TITLE
issue with creating api server using pnpx

### ISSUE THREAD

**Issue by ZhengRui** [jherr/create-mf-app#45]
I am following your tutorials of https://www.youtube.com/watch?v=lKKsjpH09dU , when I do `pnpx create-mf-app` I got this error. Creating `applications` are all fine, but creating `api server` seems all have this issue. How to solve this issue ? Thanks.

```bash
.../share/pnpm/store/v3/tmp/dlx-28313    |  +73 +++++++
.../share/pnpm/store/v3/tmp/dlx-28313    | Progress: resolved 73, reused 73, downloaded 0, added 73, done
? Pick the name of your app: server
? Project Type: API Server
? Port number: 8080
? Template: nestjs-auth
Your 'server' project is ready to go.

Next steps:

▶️ cd server
▶️ npm install
▶️ npm start

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.4.0
 ERROR  Command failed with exit code 1: create-mf-app

pnpm: Command failed with exit code 1: create-mf-app
    at makeError (/home/jerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:24235:17)
    at handlePromise (/home/jerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:24806:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/zerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:212312:7)
    at async /home/jerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:221644:21
    at async main (/home/jerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:221611:34)
    at async runPnpm (/home/jerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:221866:5)
    at async /home/jerry/.local/share/pnpm/global/5/.pnpm/pnpm@8.1.1/node_modules/pnpm/dist/pnpm.cjs:221858:7
```

**Comment by jherr** [comment]
Are you on Windows? I'm not seeing this error. If you are on Windows you should run on WSL2.

**Comment by ZhengRui** [comment]
yes I am on WSL2. In the end I solved the issue by cloning the folder in this repo.

**Comment by rajatetc** [comment]
I am facing the same issue. I am on Mac.
